describe('GX3-5422| ToolsQA | Widgets | Dropdown - Select Menu', () => {
	beforeEach('User is on the website DemoQA', () => {
		cy.visit('https://demoqa.com/select-menu');
		cy.url().should('contain', 'select-menu');
		cy.get('h1').should('have.text', 'Select Menu');
	});
	it('5437 | TC1: Validate user can select every option one at a time inside the Select Value Drop down', () => {
		cy.get('#withOptGroup').click();
		cy.get('.css-26l3qy-menu').contains('Group 1, option 1').click();
		cy.get('.css-1uccc91-singleValue').should('have.text', 'Group 1, option 1');
		cy.get('#withOptGroup').click();
		cy.get('.css-26l3qy-menu').contains('Group 1, option 2').click();
		cy.get('.css-1uccc91-singleValue').should('have.text', 'Group 1, option 2');
		cy.get('#withOptGroup').click();
		cy.get('.css-26l3qy-menu').contains('Group 2, option 1').click();
		cy.get('.css-1uccc91-singleValue').should('have.text', 'Group 2, option 1');
		cy.get('#withOptGroup').click();
		cy.get('.css-26l3qy-menu').contains('Group 2, option 2').click();
		cy.get('.css-1uccc91-singleValue').should('have.text', 'Group 2, option 2');
	});
	it('5437 | TC2: Validate user can select every option one at a time inside the Select One Drop down', () => {
		cy.get('#selectOne').click();
		cy.get('.css-26l3qy-menu').contains('Dr.').click();
		cy.get('.css-1uccc91-singleValue').should('have.text', 'Dr.');
		cy.get('#selectOne').click();
		cy.get('.css-26l3qy-menu').contains('Mr.').click();
		cy.get('.css-1uccc91-singleValue').should('have.text', 'Mr.');
		cy.get('#selectOne').click();
		cy.get('.css-26l3qy-menu').contains('Mrs.').click();
		cy.get('.css-1uccc91-singleValue').should('have.text', 'Mrs.');
		cy.get('#selectOne').click();
		cy.get('.css-26l3qy-menu').contains('Ms.').click();
		cy.get('.css-1uccc91-singleValue').should('have.text', 'Ms.');
		cy.get('#selectOne').click();
		cy.get('.css-26l3qy-menu').contains('Prof.').click();
		cy.get('.css-1uccc91-singleValue').should('have.text', 'Prof.');
		cy.get('#selectOne').click();
		cy.get('.css-26l3qy-menu').contains('Other').click();
		cy.get('.css-1uccc91-singleValue').should('have.text', 'Other');
	});
	it('5437 | TC3: Validate user can select every option one at a time inside the Old Style Select Menu', () => {
		cy.get('#oldSelectMenu').select('Red');
		cy.get('#oldSelectMenu').find('option:selected').should('have.value', 'red');
		cy.get('#oldSelectMenu').select('Blue');
		cy.get('#oldSelectMenu').find('option:selected').should('have.value', '1');
		cy.get('#oldSelectMenu').select('Green');
		cy.get('#oldSelectMenu').find('option:selected').should('have.value', '2');
		cy.get('#oldSelectMenu').select('Yellow');
		cy.get('#oldSelectMenu').find('option:selected').should('have.value', '3');
		cy.get('#oldSelectMenu').select('Purple');
		cy.get('#oldSelectMenu').find('option:selected').should('have.value', '4');
		cy.get('#oldSelectMenu').select('Black');
		cy.get('#oldSelectMenu').find('option:selected').should('have.value', '5');
		cy.get('#oldSelectMenu').select('White');
		cy.get('#oldSelectMenu').find('option:selected').should('have.value', '6');
		cy.get('#oldSelectMenu').select('Voilet');
		cy.get('#oldSelectMenu').find('option:selected').should('have.value', '7');
		cy.get('#oldSelectMenu').select('Indigo');
		cy.get('#oldSelectMenu').find('option:selected').should('have.value', '8');
		cy.get('#oldSelectMenu').select('Magenta');
		cy.get('#oldSelectMenu').find('option:selected').should('have.value', '9');
		cy.get('#oldSelectMenu').select('Aqua');
		cy.get('#oldSelectMenu').find('option:selected').should('have.value', '10');
	});
	it('5437 | TC4: Validate user can select all the options inside the Multiselect Drop down', () => {
		cy.get('.css-1wy0on6').eq(2).click();
		cy.get('.css-26l3qy-menu').contains('Green').click();
		cy.get('.css-26l3qy-menu').contains('Blue').click();
		cy.get('.css-26l3qy-menu').contains('Black').click();
		cy.get('.css-26l3qy-menu').contains('Red').click();
		cy.get('.css-1hwfws3').eq(2).should('contain', 'Green');
		cy.get('.css-1hwfws3').eq(2).should('contain', 'Blue');
		cy.get('.css-1hwfws3').eq(2).should('contain', 'Black');
		cy.get('.css-1hwfws3').eq(2).should('contain', 'Red');
	});
	it('5437 | TC5: Validate user can clear every option inside the Multiselect Drop down', () => {
		cy.get('.css-1wy0on6').eq(2).click();
		cy.get('.css-26l3qy-menu').contains('Green').click();
		cy.get('.css-26l3qy-menu').contains('Blue').click();
		cy.get('.css-26l3qy-menu').contains('Black').click();
		cy.get('.css-26l3qy-menu').contains('Red').click();
		cy.get('.css-xb97g8').eq(0).click();
		cy.get('.css-1hwfws3').eq(2).should('not.contain', 'Green');
		cy.get('.css-xb97g8').eq(0).click();
		cy.get('.css-1hwfws3').eq(2).should('not.contain', 'Blue');
		cy.get('.css-xb97g8').eq(0).click();
		cy.get('.css-1hwfws3').eq(2).should('not.contain', 'Black');
		cy.get('.css-xb97g8').eq(0).click();
		cy.get('.css-1hwfws3').eq(2).should('not.contain', 'Red');
	});
	it('5437 | TC6: Validate user can select every option one at a time inside the Standart Multi Select', () => {
		cy.get('#cars').select('Volvo');
		cy.get('#cars').find('option:selected').should('have.value', 'volvo');
		cy.get('#cars').select('Saab');
		cy.get('#cars').find('option:selected').should('have.value', 'saab');
		cy.get('#cars').select('Opel');
		cy.get('#cars').find('option:selected').should('have.value', 'opel');
		cy.get('#cars').select('Audi');
		cy.get('#cars').find('option:selected').should('have.value', 'audi');
	});
});
