
describe('GX3-2176_⚡️ToolsQA | Widgets | Dropdown - Select Menu ',() => {
	beforeEach('Prc: Usuario debe ingresar a la pagina para hacer pruebas',() => {
	    cy.visit('/select-menu');
	});
	it('2176| TC1: Validar poder seleccionar un elemento de la lista desplegable de "Select Value" ', () => {;
		cy.get('#withOptGroup').click();
		cy.get('#react-select-2-option-0-0').click();
		cy.contains('Group 1, option 1');
	});
	it('2176| TC2: Validar poder seleccionar un titulo de la lista desplegable de "Select One" ', () => {;
		cy.get('#selectOne').click();
		cy.get('#react-select-3-option-0-2').click();
		cy.contains('Mrs.');
	});
	it('2176| TC3: Validar poder seleccionar un color de la lista desplegable de "Old Style Select Menu" ', () => {;
		cy.get('#oldSelectMenu').select('Red');
		cy.contains('Red');
	});
	it('2176| TC4: Validar poder seleccionar uno o mas elementos del "Multiselect drop down" ', () => {;
		cy.get('.css-1wa3eu0-placeholder').eq(2).click();
		cy.get('#react-select-4-option-0').click();
		cy.get('#react-select-4-option-1').click();
		cy.get('#react-select-4-option-2').click();
		cy.get('#react-select-4-option-3').click();
		cy.contains('Green');
		cy.contains('Blue');
		cy.contains('Black');
		cy.contains('Red');
	});
	it('2176| TC5: Validar poder seleccionar varios elementos del menú "Standard multi select" ', () => {;
		cy.get('#cars').select('Volvo');
		cy.get('#cars').select('Saab');
		cy.get('#cars').select('Opel');
		cy.get('#cars').select('Audi');
		cy.contains('Volvo');
		cy.contains('Saab');
		cy.contains('Opel');
		cy.contains('Audi');
	});
});