describe('GX3-5427 | ToolsQA | Elements | Checkbox', () => {
	beforeEach(() => {
		cy.visit('https://demoqa.com/checkbox');
		cy.url().should('include', '/checkbox');
		cy.get('h1.text-center').should('have.text', 'Check Box');
	});
	it('GX3- 5489 | TC1: Validar expandir y contaer la carpeta "Home" desde los botones expand all y contrat all.', () => {
		cy.get('.rct-icon.rct-icon-expand-all').click();
		cy.get('.rct-icon.rct-icon-uncheck').eq(0).click();
		cy.contains('Home').should('be.visible');
		cy.contains('Desktop').should('be.visible');
		cy.contains('Notes').should('be.visible');
		cy.contains('Commands').should('be.visible');
		cy.contains('Documents').should('be.visible');
		cy.contains('WorkSpace').should('be.visible');
		cy.contains('React').should('be.visible');
		cy.contains('Angular').should('be.visible');
		cy.contains('Veu').should('be.visible');
		cy.contains('Office').should('be.visible');
		cy.contains('Public').should('be.visible');
		cy.contains('Private').should('be.visible');
		cy.contains('Classified').should('be.visible');
		cy.contains('General').should('be.visible');
		cy.contains('Downloads').should('be.visible');
		cy.contains('Word File.doc').should('be.visible');
		cy.contains('Excel File.doc').should('be.visible');
		cy.get('span.text-success').should('contain.text', 'homedesktopnotescommandsdocumentsworkspacereactangularveuofficepublicprivateclassifiedgeneraldownloadswordFileexcelFile');
		cy.get('.rct-icon.rct-icon-check').eq(0).click({ multiple: true });
		cy.get('.rct-icon.rct-icon-collapse-all').click();
	});
	it('GX3-5489 | TC2: Validar expandir y contraer la carpeta "Home" y al hacerle check se marquen o desmarquen las carpetas "Desktop", "Documents" y "Downloads".', () => {
		cy.get('.rct-icon.rct-icon-expand-close').click();
		cy.get('.rct-icon.rct-icon-uncheck').eq(0).click({ multiple: true });
		cy.contains('Home').should('be.visible');
		cy.contains('Desktop').should('be.visible');
		cy.contains('Documents').should('be.visible');
		cy.contains('Downloads').should('be.visible');
		cy.get('span.text-success').should('be.visible', 'desktopdocumentsdownloads');
		cy.get('.rct-icon.rct-icon-check').eq(0).click({ multiple: true });
		cy.get('.rct-icon.rct-icon-expand-open').click();
	});
	it('GX3-5489 | TC3: Validar expandir y contraer la carpeta "Desktop" y al hacerle check se marquen las subcarpetas "Notes" y "Commands".', () => {
		cy.get('.rct-icon.rct-icon-expand-close').click();
		cy.get('.rct-icon.rct-icon-expand-close').eq(0).click();
		cy.get('.rct-icon.rct-icon-uncheck').eq(1).click({ multiple: true });
		cy.contains('Desktop').should('be.visible');
		cy.contains('Notes').should('be.visible');
		cy.contains('Commands').should('be.visible');
		cy.get('span.text-success').should('contain.text', 'desktopnotescommands');
		cy.get('.rct-icon.rct-icon-check').eq(1).click();
		cy.get('.rct-icon.rct-icon-check').eq(0).click({ multiple: true });
		cy.get('.rct-icon.rct-icon-expand-open').eq(1).click();
		cy.get('.rct-icon.rct-icon-expand-open').eq(0).click();
	});
	it('GX3-5489 | TC4: Validar expandir y contraer la carpeta "Documents" y al hacerle check se marquen las subcarpetas "WorkSpace" y "Office".', () => {
		cy.get('.rct-icon.rct-icon-expand-close').click();
		cy.get('.rct-icon.rct-icon-expand-close').eq(1).click();
		cy.get('.rct-icon.rct-icon-uncheck').eq(2).click({ multiple: true });
		cy.contains('Documents').should('be.visible');
		cy.contains('WorkSpace').should('be.visible');
		cy.contains('Office').should('be.visible');
		cy.get('span.text-success').should('contain.text', 'documentsworkspacereactangularveuofficepublicprivateclassifiedgeneral');
		cy.get('.rct-icon.rct-icon-check').eq(1).click();
		cy.get('.rct-icon.rct-icon-check').eq(0).click({ multiple: true });
		cy.get('.rct-icon.rct-icon-expand-open').eq(1).click();
		cy.get('.rct-icon.rct-icon-expand-open').eq(0).click();
	});
	it('GX3-5489 | TC5: Validar expandir y contraer la subcarpeta "WorkSpace" y al hacerle check se marquen "React", "Angular" y "Veu".', () => {
		cy.get('.rct-icon.rct-icon-expand-close').click();
		cy.get('.rct-icon.rct-icon-expand-close').eq(1).click();
		cy.get('.rct-icon.rct-icon-expand-close').eq(1).click();
		cy.get('.rct-icon.rct-icon-uncheck').eq(3).click({ multiple: true });
		cy.contains('Documents').should('be.visible');
		cy.contains('WorkSpace').should('be.visible');
		cy.contains('React').should('be.visible');
		cy.contains('Angular').should('be.visible');
		cy.contains('Veu').should('be.visible');
		cy.get('span.text-success').should('contain.text', 'workspacereactangularveu');
		cy.get('.rct-icon.rct-icon-check').eq(0).click({ multiple: true });
		cy.get('.rct-icon.rct-icon-expand-open').eq(2).click();
		cy.get('.rct-icon.rct-icon-expand-open').eq(1).click();
		cy.get('.rct-icon.rct-icon-expand-open').eq(0).click();
	});
	it('GX3-5489 | TC6: Validar expandir y contraer la subcarpeta "Oficce" y al hacerle check se marquen "Public", "Private", "Classified" y "General".', () => {
		cy.get('.rct-icon.rct-icon-expand-close').click();
		cy.get('.rct-icon.rct-icon-expand-close').eq(1).click();
		cy.get('.rct-icon.rct-icon-expand-close').eq(2).click();
		cy.get('.rct-icon.rct-icon-uncheck').eq(4).click({ multiple: true });
		cy.contains('Documents').should('be.visible');
		cy.contains('Office').should('be.visible');
		cy.contains('Public').should('be.visible');
		cy.contains('Private').should('be.visible');
		cy.contains('Classified').should('be.visible');
		cy.contains('General').should('be.visible');
		cy.get('span.text-success').should('contain.text', 'officepublicprivateclassifiedgeneral');
		cy.get('.rct-icon.rct-icon-check').eq(0).click({ multiple: true });
		cy.get('.rct-icon.rct-icon-expand-open').eq(2).click();
		cy.get('.rct-icon.rct-icon-expand-open').eq(1).click();
		cy.get('.rct-icon.rct-icon-expand-open').eq(0).click();
	});
	it('GX3-5489 | TC7: Validar expandir y contraer la carpeta "Downloads" y al hacerle check se marquen "Word File.doc" y "Excel File.doc".', () => {
		cy.get('.rct-icon.rct-icon-expand-close').click();
		cy.get('.rct-icon.rct-icon-expand-close').eq(2).click();
		cy.get('.rct-icon.rct-icon-uncheck').eq(3).click({ multiple: true });
		cy.contains('Downloads').should('be.visible');
		cy.contains('Word File.doc').should('be.visible');
		cy.contains('Excel File.doc').should('be.visible');
		cy.get('span.text-success').should('contain.text', 'downloadswordFileexcelFile');
		cy.get('.rct-icon.rct-icon-check').eq(2).click();
		cy.get('.rct-icon.rct-icon-check').eq(0).click({ multiple: true });
		cy.get('.rct-icon.rct-icon-expand-open').eq(1).click();
		cy.get('.rct-icon.rct-icon-expand-open').eq(0).click();
	});
});
