# 🧙🏻‍♂️BIENVENIDO A LOS PIPELINES DE CONTINUOUS INTEGRATION DE "ARI - Hija de Aurora"!
# 🤖Este Pipeline de CI se activa al PUSHEAR, y consiste en ejecutar los tests de una US e importar los resultados a Jira!🚀
# 👩🏻‍🔬Para utilizar este Pipeline de Ari, sigue los siguientes pasos:
#     1ro: debes modificar el script: "npm run file" + tu archivo de Prueba Ejecutable (ver ejemplo en este archivo) 
#     2do: debes modificar la propiedad: "testExecKey:" + tu ID del TX de Jira para importar automáticamente el resultado.
#     3ro: guarda los cambios en el repositorio local (git add + git commit) y envíalos al Repo Remoto (git push)
#     Expected Result: Debería ejecutarse este Pipeline de GitHub Actions y correr cada uno de los Jobs declarados aquí. 

name: 🤖CI run (BUILD) Test Suite Execution⚡
run-name: ${{github.actor}}👨🏻‍🔬 run Test Suite in ${{github.ref_name}}

on: # This Run is a template. The correct "Run On" should be: Any except QA and Main (cypex)
  push:
    branches-ignore:
      - cypex
      - QA

jobs:
    Build-Cypress-TestSuite-AfterPush:
        runs-on: ubuntu-latest

        steps:
            - name: 💻Checkout
              uses: actions/checkout@v3

            - name: 💿Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: 🧬Install All Dependencies
              run: |
                npm install
                npm list 

            - name: 🧪Cypress Build and Run US Test Coverage in Chrome
              uses: cypress-io/github-action@v4
              with:
                  browser: chrome
                  command: | #EDITAR AQUÍ EL ARCHIVO SUITE A EJECUTAR:
                    npm run file */**/GX-5644/*.cy.js
                  record: true #HABILITAR A TRUE* cuando se use un Proyecto.
              env:
                  # pass the Dashboard record key as an environment variable
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPEX_DEMO_RECORD_KEY }}
                  # pass GitHub token to allow accurately detecting a build vs a re-run build
                  GITHUB_TOKEN: ${{ secrets.UPEX_GITHUB_TOKEN }}

            - name: 📊Upload Artifact HTML Report
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: test-report
                  path: mochawesome-report

            - name: ✅Import Test Results to Xray
              if: always()
              uses: mikepenz/xray-action@v2
              with: #EDITAR AQUÍ EL TEST EXECUTION DE JIRA DONDE SE CARGARÁN LOS TESTS:
                  username: ${{secrets.XRAY_CLIENT_ID}}
                  password: ${{secrets.XRAY_CLIENT_SECRET}}
                  testFormat: 'junit'
                  testPaths: 'reports/test-results.xml'
                  testExecKey: 'GX-5646'
                  projectKey: 'GX'

            - name: 🔔Slack Notification of Done
              if: always()
              uses: rtCamp/action-slack-notify@v2.2.0
              env:
                SLACK_WEBHOOK: https://hooks.slack.com/services/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
                SLACK_USERNAME: Ari✨
                SLACK_MESSAGE: ':test_tube: Test Execution successfully imported to Jira-Xray :rocket:'
                SLACK_COLOR: ${{ job.status }}
                SLACK_ICON: https://i.imgur.com/peg9swL.png

