name: CI run Regression in Parallel
run-name: ${{github.actor}} CI run Regression in Parallel ${{github.ref_name}}

on:
    push:
        branches:
            - TX-Parallel

jobs:
    RegressionTestInteractions:
        name: Regression Test - Interactions
        runs-on: ubuntu-latest
        steps:
            # Setup steps
            - name: 💻Checkout
              uses: actions/checkout@v3
            - name: 💿Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: 💿Yarn Setup
              uses: DerYeger/yarn-setup-action@master
              with:
                  node-version: 16
            - name: 🧬Install All Dependencies
              run: yarn
            # Test step
            - name: 🧪Cypress E2E Regression Test of Interactions
              uses: cypress-io/github-action@v4
              with:
                  browser: chrome
                  command: yarn regression:interactions
            # After script steps
            - name: 📬Generate XML Regression Report
              if: always()
              run: yarn report:xml
            - name: ✅Import Test Results to Xray
              if: always()
              uses: mikepenz/xray-action@v2
              with:
                  username: ${{secrets.XRAY_CLIENT_ID}}
                  password: ${{secrets.XRAY_CLIENT_SECRET}}
                  testFormat: 'junit'
                  testPaths: 'reports/regression-report.xml'
                  testExecKey: 'GX-3704'
                  projectKey: 'GX'
            - name: 📬Generate Allure Regression Report
              if: always()
              run: yarn allure:ci
            - name: 📊Upload Artifact Allure
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: regression-allure-report
                  path: reports/allure-report

    RegressionTestWidgets:
        name: Regression Test - Widgets
        runs-on: ubuntu-latest
        steps:
            # Setup steps (same as above)
            - name: 💻Checkout
              uses: actions/checkout@v3
            - name: 💿Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: 💿Yarn Setup
              uses: DerYeger/yarn-setup-action@master
              with:
                  node-version: 16
            - name: 🧬Install All Dependencies
              run: yarn
            # Test step
            - name: 🧪Cypress E2E Regression Test of Widgets
              uses: cypress-io/github-action@v4
              with:
                  browser: chrome
                  command: yarn regression:widgets
            # After script steps (same as above)
            - name: 📬Generate XML Regression Report
              if: always()
              run: yarn report:xml
            - name: ✅Import Test Results to Xray
              if: always()
              uses: mikepenz/xray-action@v2
              with:
                  username: ${{secrets.XRAY_CLIENT_ID}}
                  password: ${{secrets.XRAY_CLIENT_SECRET}}
                  testFormat: 'junit'
                  testPaths: 'reports/regression-report.xml'
                  testExecKey: 'GX-3704'
                  projectKey: 'GX'
            - name: 📬Generate Allure Regression Report
              if: always()
              run: yarn allure:ci
            - name: 📊Upload Artifact Allure
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: regression-allure-report
                  path: reports/allure-report
