name: 🧪Ely's Pipeline SanityTest
run-name: ${{github.actor}}👨🏻‍🔬 triggered SanityTest in ${{github.ref_name}}

on:
  push:
    branches: ['test/GX3-4236/dropdown_select_menu'] #! Cambia "TuBranchAqui" por el nombre de tu rama de tarea.

jobs:
  SanityTest:
    runs-on: ubuntu-latest

    steps:
    - name: 💻Checkout
      uses: actions/checkout@v4

    - name: 💿Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 🍙 Bun Setup
      uses: oven-sh/setup-bun@v1

    - name: 🧬Install All Dependencies
      run: |
        bun install

    - name: 🧪Cypress Run Test Coverage
      uses: cypress-io/github-action@v4
      with:
        browser: chrome
        command: | #todo: EDITAR AQUÍ EL ARCHIVO SUITE A EJECUTAR:
          bun run test:chrome cypress/e2e/Tests/Widgets/GX3-4236-Dropdown-Select.cy.ts
      env:
        CYPRESS_ENVIRONMENT: 'prod'

    - name: 📬Generate JUnit/Mocha Report
      if: always()
      run: |
        bun run chrome:report

    - name: ✅Import Test Results to Xray
      if: env.XRAY_CLIENT != '' && env.XRAY_SECRET != '' #? Corre este paso si la variable de entorno está definida
      uses: mikepenz/xray-action@v3
      with: #OPCIONES PARA IMPORTAR LOS RESULTADOS DE PRUEBA A JIRA XRAY:
        username: ${{ env.XRAY_CLIENT}}
        password: ${{ env.XRAY_SECRET}}
        testFormat: 'junit' #! NO CAMBIAR
        testPaths: 'cypress/tests_results/junit/chrome_regression_report.xml' #! NO CAMBIAR
        testExecKey: 'GX3-4243' #todo: EDITAR AQUÍ EL TEST EXECUTION A IMPORTAR LAS PRUEBAS.
        projectKey: 'GX3' #todo: EDITAR EN CASO DE TRABAJAR CON OTRO PROYECTO.
      env:
        XRAY_CLIENT: ${{ secrets.XRAY_CLIENT_ID }}
        XRAY_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}

    - name: 📊Upload Artifact Mochawesome Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sanity-mocha-report
        path: cypress/tests_reports/chrome_mocha_report
        retention-days: 15

    - name: 🚀Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./cypress/tests_reports/chrome_mocha_report
        destination_dir: sanity
        # by default, this report will be deployed to branch: gh-pages

    - name: 🔔Slack Notification of Done
      if: env.SLACK_WEBHOOK != '' #? Corre este paso si la variable de entorno está definida
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Ari✨
        SLACK_MESSAGE: ':test_tube: (CYPRESS) PROJECT: ToolsQA: TEST SUITE RESULTS IMPORTED TO JIRA :rocket:'
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://image.cdn2.seaart.ai/2023-12-06/clo9g0h4msbc73ac2sog/99e1abc36f32945cd4bacf5ee7448e96194545f7_high.webp
